### ISSUE TITLE
Using web.config app settings in MD links

### ISSUE THREAD

**Issue by TyreeC100** [jmalarcon/MIIS#21]
Hi,

  I have been using MIIS to set up a portal site that needs to access content from other servers.  Rather than hardcode the URL into the files I wanted to create a variable to store the base path.  I added to the web.config the key.
   `<add key="MIIS:videos" value="http://server_name/VideoSite"/>` 

  Now in the MD file I am having problems using the key.  I can use the following
    `<a href="{{videos}}/index.html">Test vid1</a>`

  But, this does not evaluate to the same html.
    `[Test vid2]({{videos}}/index.html)`

  I have tried googling, but not with much success.  Any pointers would be appreciated.

Many thanks.

**Comment by jmalarcon** [comment]
I see...

I'm afraid Markdig, which is the library I use to render the markdown, acts correctly and automatically encodes unsafe characters in a URL to prevent possible security problems. 

[RFC 1738](http://tools.ietf.org/html/rfc1738) states that certain characters are unsafe in URLs:

>...Other characters are unsafe because gateways and other transport agents are known to sometimes modify such characters. These characters are "{", "}", "|", "\", "^", "~", "[", "]", and "`".
>
>All unsafe characters must always be encoded within a URL.

So the `{` symbol should be replaced with `%7B` and `}` with `%7D` and that's what's happening.

Your only option as of today is to replace the markdown links with real HTML links. You can mix HTML and markdown in your file without problem if you start the HTML lines without any spaces at the beginning.

I can try to see the implications of un-encoding those specific two characters in the initial HTML resulting from the markdown conversion in order to cover these cases. Maybe it could be useful for some specific cases like this one.

I've used this kind of placeholders to reuse URLs or parts of URLS but always in templates, not in links inside documents. If you use it in a template, since they don't go through Markdig it would be OK using them there.

I'll keep the issue open to take a look as soon as I can.

HTH

P.S.: By the way, if your site goes public, please send me a line in Twitter to tell me. I'm collecting some examples of MIIS in real use and it would help, specially if you create a custom template for it.

**Comment by TyreeC100** [comment]
Hi, thanks for the quick reply.

It makes sense for the URL to be made safe.  Writing the html in the markdown file is a good workaround for now since I can tell our content writers to use that style for external links, and markdown for internal.

Unfortunately the final portal will not be available publicly, but I will check to see if there would be any issue to make available the template used.

Many thanks.

**Comment by jmalarcon** [comment]
Thanks! It would be great to have more templates available.

I'll let you know if I add support for templates inside links anyway.

Best regards.

**Comment by jmalarcon** [comment]
Hi,

This is fixed in the new version 3.0.0 that is going to be ready very soon!
