### ISSUE TITLE
Using a template reference in `toc` is not evaluated if not mentioned in the base md file

### ISSUE THREAD

**Issue by DenisValeev** [jmalarcon/MIIS#26]
Suppose you have a `toc` file in which you reference `{{a}}` which is defined in the `web.config` as a reference to the `~\a.md` file. Then you have a file named `b.md`. When you open `/b.md` the `{{a}}` doesn't get evaluated in the `toc` section of the render if and only if it is not mentioned in the `b.md` file.

**Comment by jmalarcon** [comment]
Hi Denis:

I can't reproduce that behavior. Can you attach a ZIP with the exact files in the sample (including `web.config` and any subfolders that may be)?

Thanks.

**Comment by DenisValeev** [comment]
Thanks for looking into this matter. In the `docs.zip` I made a working example. `index.md` demonstrates that the `{{links}}` directive is not evaluated. And the `ok.md` demonstrates that it is evaluated when mentioned in the `ok.md` file (commented out in html).

[docs.zip](https://github.com/jmalarcon/MIIS/files/2900321/docs.zip)

**Comment by jmalarcon** [comment]
I see what you mean now... OK, this is the expected behavior. You can't include file fields inside other file fields, since that could lead to circular references or infinite (or at least very long) processing if everytime you include a file there would be more fields to process. 

The only sub-processing that is made, is for [includes in templates](https://miis.azurewebsites.net/Templating#includes-in-templates). Includes allow to use other includes inside them and MIIS takes into account possible circular references and warns you about that.

In fields that are files and therefore are processed and inserted into the main content, this won't work, because in fact that should not be needed either. 

If you take into account the [processing order in the pipeline for MIIS pages](https://miis.azurewebsites.net/Templating#processing-order) you can see that custom fields, including file fields like the one you're using, are processed at the end, and in one step. If you insert some content that includes more custom fields, those extra fields are not processed again.

Just add that kind of fields in the template (or in an include for the current template) and you'll get the same effect.

HTH

**Comment by DenisValeev** [comment]
> or in an include for the current template
That's exactly what I did. Thanks!
