### ISSUE TITLE
IIS 10 issue

### ISSUE THREAD

**Issue by k1ngf15h3r** [jmalarcon/MIIS#3]
Hi man, 

I really looking forward to test MIIS on my Windows 10 maschine but I can not get it to run under IIS 10.
I managed all issues for now but after getting directory listing enabled and clicking the default.md file I got a new error:
```
HTTP-Fehler 500.21 - Internal Server Error
Der Handler ".md extension" weist das ungültige Modul "ManagedPipelineHandler" in der Modulliste auf.
[...]
Modul | IIS Web Core
-- | --
ExecuteRequestHandler
.md extension
0x8007000d
```

Any hints for this? I am really new to IIS .. coming from apache and nginx ;)

**Comment by jmalarcon** [comment]
Hi:

You shouldn't have any problems running it in IIS 10. You only need ASP.NET 3.x or later enabled and you're done. By default they should be enabled.

If it's not, you can execute this from the command line:

```
C:\Windows\Microsoft.NET\Framework64\v4.0.30128\aspnet_regiis.exe -ir
```

and it should work

If it's still not working after that, register ASP.NET into IIS using this command:

```
C:\Windows\Microsoft.NET\Framework64\v4.0.30319>dism /online /enable-feature /featurename:IIS-ASPNET45
```

Please, let me know if this fixes the problem. Thanks.

**Comment by k1ngf15h3r** [comment]
Hi,

after I added Asp.net it was working, but only when I add MISS as default
site. As virtual Directory I got errors because Module feature is disabled
in virtual directories.

Any idea for this?


Am 27.09.2017 13:21 schrieb "José M. Alarcón" <notifications@github.com>:

**Comment by jmalarcon** [comment]
Hi again:

OK, that's a totally different problem.

What is probably happening to you is that your virtual directory is not only that, but a virtual application, with is a different kind of beast.

An application basically defines a directory, and all sub-directories, as existing within one application environment. It means that the application folder is **the root for a new app** and it can have it's own process/application pool and it's completely separated from your main app.

The error you are receiving is due to **certain configurations that can only be defined for an application as a whole**.

You should read [this article](https://docs.microsoft.com/en-us/iis/get-started/planning-your-iis-architecture/understanding-sites-applications-and-virtual-directories-on-iis) that explains pretty well the differences.

You should convert the virtual app into a virtual directory (the best way to go would be to delete irt and create it again).

You can try to use the `web.config` in the root folder for the whole site and test it.

A more complicated approach would be [this one](https://weblog.west-wind.com/posts/2007/Aug/11/IISASPNET-Settings-and-Virtual-Directory-Inheritance).

My advice would be not to use virtual directories or virtual apps if you can avoid them.

HTH

**Comment by k1ngf15h3r** [comment]
I will try this out. Sorry I am totally new on iis hosting ;)

Thanks for you help.



Am 27.09.2017 20:44 schrieb "José M. Alarcón" <notifications@github.com>:

**Comment by jmalarcon** [comment]
You're welcome. I hope you can take advantage of it.

Pay attention to the new `.mdh` file type I've added recently. It will help you to create more HTML-oriented sites based in MIIS, useful for more things than documentation only. I plan to add moe features in the next weeks, as soon as I have the time.

I'm closing the issue now.

Cheers!
