### ISSUE TITLE
Feature request: Is there a way to support PlantUML or mermaid? Would be great if UML diagrams could also be rendered!

### ISSUE THREAD

**Issue by ritti** [jmalarcon/MIIS#32]

**Comment by jmalarcon** [comment]
Hi:

Mermaid and nomnoml diagrams are enabled by default in MIIS 3.0+. 

Just add a code block with the `mermaid` language, for example:

```````````````````````````````` example
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
````````````````````````````````

and instead of a typical `<pre><code>` you'll get a `<div class="mermaid">`:

```````````````````````````````` example
<div class="mermaid">graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
</div>
````````````````````````````````

In this way you just need to add the mermaid renderer to your page:

```html
<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
<script>mermaid.initialize({startOnLoad:true});</script>
```

And it will create the diagrams. Easy, peasy.

Regarding PlantUML, I guess you could adapt any JavaScript viewer easily (such as [this one for markdown-it](https://github.com/gmunguia/markdown-it-plantuml)) and define the diagrams with `:::{.plantuml}` blocks so that they can be rendered, but I don't have any experience with this.

HTH
