### ISSUE TITLE
Invalid template: The {{content}} placeholder must be present! 

### ISSUE THREAD

**Issue by tmfo** [jmalarcon/MIIS#6]
Hello,
I am downloaded your latest MIIS Source Code to me.
But unfortunately the compiled result does not work anymore.
The used templates are in your Source Code, below UI_Templates.
I always get the error:

```
Invalid template: The {{content}} placeholder must be present! 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.Exception: Invalid template: The {{content}} placeholder must be present!

Source Error: 
Line 171:                    throw new Exception("Invalid template: The " + FIELD_PREFIX + "content" + FIELD_SUFIX + " placeholder must be present!"); 
Line 172:
Line 173:                HttpRuntime.Cache.Insert(templatePath, templateContents, new CacheDependency(templatePath)); //Add result to cache with dependency on the file
Line 174:                return templateContents; //Return content
Line 175:            }
  

 Source File:  c:\TFS_WS\Git\MIIS\src\MIISHandler\Helper.cs    Line:  173 

Stack Trace: 


[Exception: Invalid template: The {{content}} placeholder must be present!]
   MIISHandler.Helper.readTemplate(String templateVirtualPath, HttpContext ctx) in c:\TFS_WS\Git\MIIS\src\MIISHandler\Helper.cs:173
   MIISHandler.HTMLRenderer.RenderMarkdown(MarkdownFile md) in c:\TFS_WS\Git\MIIS\src\MIISHandler\HTMLRenderer.cs:43
   MIISHandler.MarkdownFile.get_HTML() in c:\TFS_WS\Git\MIIS\src\MIISHandler\MarkdownFile.cs:115
   MIISHandler.MIISHandler.ProcessRequest(HttpContext ctx) in c:\TFS_WS\Git\MIIS\src\MIISHandler\MIISHandler.cs:74
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +599
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +171
```

**Comment by jmalarcon** [comment]
Hi:

I'm in the process of updating the software. I've been working hard lately on version 2.0 and I expect to launch a new release (compiled version) and updated documentation anytime soon. 

In v2.0 a lot of things have changed (I've done several important breaking changes, hene the version bump, since I use Semantic version) and there are a lot of new features such as fragments, includes in templates, etc..., so I need time to update the docs.

Meanwhile you can use the latest release (1.1.1) with the old templates, and they should work flawlessly.

In one of the latest commits today I've updated all the default templates, and they work OK with the latest version. In fact I've got rid of the `UI_Templates` folder and the templates are now under the source code folder, making them easier to test.

In the new documentation I'll add migration instructions, although it is going to be quite simple.

Please be patient since I'm doing this during my free time. Thanks.

I'll notify you through this issue when everything is ready.

Best regards.

**Comment by jmalarcon** [comment]
Version 2.0 of MIIS is available with updated templates and documentation. Check it out: https://github.com/jmalarcon/MIIS/releases
